export enum Command {
  // User and Auth Commands
  REGISTRATION = 'REGISTRATION',
  LOGIN = 'LOGIN',
  FORGET_PASSWORD = 'FORGET_PASSWORD',
  UPDATE_USER = 'UPDATE_USER',

  // Role Commands
  CREATE_ROLE = 'CREATE_ROLE',
  FIND_ALL_ROLES = 'FIND_ALL_ROLES',
  FIND_ONE_ROLE = 'FIND_ONE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  REMOVE_ROLE = 'REMOVE_ROLE',

  // Permission Commands
  CREATE_PERMISSION = 'CREATE_PERMISSION',
  CREATE_BULK_PERMISSION = 'CREATE_BULK_PERMISSION',
  FIND_ALL_PERMISSIONS = 'FIND_ALL_PERMISSIONS',
  SHOW_ROLE_PERMISSION = 'SHOW_ROLE_PERMISSION',
  FIND_ONE_PERMISSION = 'FIND_ONE_PERMISSION',
  UPDATE_PERMISSION = 'UPDATE_PERMISSION',
  REMOVE_PERMISSION = 'REMOVE_PERMISSION',

  // Assignment Commands
  ASSIGN_ROLE_TO_USER = 'ASSIGN_ROLE_TO_USER',
  ASSIGN_PERMISSION_TO_ROLE = 'ASSIGN_PERMISSION_TO_ROLE',
}
